name: mental
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-232.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get_it: ^7.2.0
  injectable: ^1.4.1

  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0

  get: ^4.6.1

  cloud_firestore: ^3.3.0
  firebase_core: ^1.18.0
  firebase_messaging: ^11.4.2
  firebase_auth: ^3.4.2


  flutter_svg: ^1.0.3

  shared_preferences: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.0
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  injectable_generator: ^1.4.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/

  # fonts:
  #   - family:  WCODIcons
  #     fonts:
  #       - asset: assets/fonts/WCODIcons.ttf
  #   - family:  Rubik
  #     fonts:
  #       - asset: assets/fonts/Rubik-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Rubik-Medium.ttf
  #         weight: 400
  #       - asset: assets/fonts/Rubik-Regular.ttf
  #         weight: 500  
  fonts:
    - family:  PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700  
